/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/miDvrT4gZGRQ86tg/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#a4b9dc']} />
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          zoom={1.23}
          far={100000}
          near={-100000}
          position={[717.44, 552.05, -424.89]}
          rotation={[-2.23, 0.8, 2.39]}
          scale={1}
        />
        <group name="bowl spoon" position={[-2.07, 81.63, -2.61]} scale={[0.66, 0.73, 0.69]}>
          <group name="Insider-Ramen" position={[113.56, 22.79, 2.49]} scale={[1.5, 1.38, 1.45]}>
            <mesh
              name="Meat"
              geometry={nodes.Meat.geometry}
              material={materials['Meat Material']}
              castShadow
              receiveShadow
              position={[-133.4, 37.65, 90.12]}
              rotation={[Math.PI / 2, 0, 2.68]}
              scale={[-15.45, 5.09, 0.01]}
            />
            <mesh
              name="egg"
              geometry={nodes.egg.geometry}
              material={materials.egg}
              castShadow
              receiveShadow
              position={[0.87, -9.93, 43.22]}
              rotation={[-0.24, -0.15, 2.13]}
              scale={[-1, 0.18, 1]}
            />
            <mesh
              name="Meat1"
              geometry={nodes.Meat1.geometry}
              material={materials['Meat1 Material']}
              castShadow
              receiveShadow
              position={[-164.85, 37.73, 36.59]}
              rotation={[1.57, -0.01, 3.1]}
              scale={[-15.39, 5.09, 0.01]}
            />
            <mesh
              name="Noodle 2"
              geometry={nodes['Noodle 2'].geometry}
              material={materials.Paper}
              castShadow
              receiveShadow
              position={[-108.78, 20.01, -8.3]}
              rotation={[1.74, 1.19, 3.04]}
              scale={[0.1, 0.34, 0.1]}
            >
              <mesh
                name="Noodle"
                geometry={nodes.Noodle.geometry}
                material={materials.Paper}
                castShadow
                receiveShadow
                position={[105.87, -115.09, 243.58]}
                rotation={[-0.15, -0.56, -0.22]}
                scale={[1, 1.06, 1]}
              />
            </mesh>
            <mesh
              name="Noodle 21"
              geometry={nodes['Noodle 21'].geometry}
              material={materials.Paper}
              castShadow
              receiveShadow
              position={[-86.21, 1.45, 10.86]}
              rotation={[1.64, -0.88, -Math.PI]}
              scale={[0.1, 0.34, 0.1]}
            />
          </group>
          <mesh
            name="bowl"
            geometry={nodes.bowl.geometry}
            material={materials.blue}
            castShadow
            receiveShadow
            position={[45.37, -111.93, 0]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1, 1, 1]}
          />
          <mesh
            name="Kuah"
            geometry={nodes.Kuah.geometry}
            material={materials['Kuah Material']}
            castShadow
            receiveShadow
            position={[44.45, 21.39, -3.95]}
            rotation={[3.13, 0, 0]}
            scale={[11.39, 5.38, 11.47]}
          />
          <mesh
            name="spoon"
            geometry={nodes.spoon.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[-94.41, 83.52, -43.42]}
            rotation={[1.56, -0.2, -1.58]}
            scale={1}
          />
        </group>
        <directionalLight
          name="Directional Light"
          intensity={2.75}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#f8f8f8"
          position={[200, 300, 300]}
          scale={[NaN, NaN, NaN]}
        />
        <mesh
          name="Rectangle"
          geometry={nodes.Rectangle.geometry}
          material={materials['Rectangle Material']}
          castShadow
          receiveShadow
          position={[0, -12.1, 0]}
          rotation={[-1.59, 0, -0.01]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#c9aeae" />
      </group>
    </>
  )
}
